# This file defines how telemetry files are to be identified and
# paired with a process that can import the file
# In order to run, do something like this:
# ./apps/xgds_core/importer/importHandler.py --user xgds --password the_password ./path/to/this/file.yaml

# Top-level directory to look for incoming files, this is overridden if the import handler is called with a path
import_path: '/home/xgds/xgds_subsea/data/incoming'

# Registry of regex patterns to look for and what to do when files match them
registry:
  - name: 'CTD'
    filepath_pattern: '[\d\.]+/processed/dive_reports/.*/sampled/(?P<flight>H\d{4}).CTD.sampled.tsv'
    importer: '/home/xgds/xgds_subsea/apps/xgds_core/importer/csvImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/CTD.yaml -f %(flight)s_Hercules'
    timeout: 300
    order: 2
    auth: false
  - name: 'chatlog_html' # ALWAYS SKIP
    filepath_pattern: '[\d\.]+/raw/chatlog/.*/.*/.*\.html'
    ignore: true
  - name: 'DS_Store'
    filepath_pattern: '.*/\.DS_Store'
    ignore: true
  - name: 'chatlog'
    filepath_pattern: '[\d\.]+/processed/eventlog/by-dive/all_chatlog_.*\.txt'
    ignore: true
