# This file defines how telemetry files are to be identified and
# paired with a process that can import the file

# Top-level directory to look for incoming files, this is overridden if the import handler is called with a path
import_path: '/home/xgds/xgds_subsea/data/incoming'

# Registry of regex patterns to look for and what to do when files match them
registry:
#  - name: 'nav_split'
#    filepath_pattern: '[\d\.]+raw/datalog/.*\.NAV'
#    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/navPreprocessor.py'
#    timeout: 300
#    order: 1
#    auth: false
  - name: 'capture'
    filepath_pattern: '[\d\.]+raw/capture/capture_.*/*\.tif'
    importer: '/home/xgds/xgds_braille/apps/xgds_image/importer/import_image.py'
    timeout: 300
    order: 5
    auth: true
  - name: 'tempprobe'
    filepath_pattern: '[\d\.]+raw/datalog/.*\.TEM'
    importer: '/home/xgds/xgds_braille/apps/xgds_core/importer/csvImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/tempprobe.yaml'
    timeout: 300
    order: 2
    auth: false
  - name: 'chatlog' # TODO IMPLEMENT
    filepath_pattern: '[\d\.]+/raw/chatlog/.*/.*/.*\.html'
    importer: '/home/xgds/xgds_braille/apps/xgds_notes/importer/import_notes.py'
    timeout: 300
    order: 2
    auth: false
    ignore: true
  - name: 'eventlog' # TODO IMPLEMENT
    filepath_pattern: '[\d\.]+/processed/eventlog/by-dive/.*\.txt'
    importer: '/home/xgds/xgds_braille/apps/xgds_notes/importer/import_notes.py'
    timeout: 300
    order: 2
    auth: false
    ignore: true
