# This file defines how telemetry files are to be identified and
# paired with a process that can import the file

# Top-level directory to look for incoming files, this is overridden if the import handler is called with a path
import_path: '/home/xgds/xgds_subsea/data/incoming'

# Registry of regex patterns to look for and what to do when files match them
registry:
#  - name: 'nav_split'
# # I am pretty sure that the file parsing is a one step process, so if this is going to generate
# # new files it will have to also process them directly.
#    filepath_pattern: '[\d\.]+raw/datalog/.*\.NAV'
#    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/navPreprocessor.py'
#    timeout: 300
#    order: 1
#    auth: false
  - name: 'dive stats'
    filepath_pattern: 'processed/dive_reports/dives-stats.tsv'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/create_dives.py'
    timeout: 300
    order: 1
  - name: 'cruise record XML'
    filepath_pattern: 'metadata/cruise-record.xml'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/create_users.py'
    arguments: '-v %(filename)s'
    timeout: 300
    order: 2
  - name: 'Nautilus NAV'
    filepath_pattern: 'processed/dive_reports/(?P<flight>H\d{4})/sampled/H\d{4}\.NAV\.PV\.sampled\.tsv'
    importer: '/home/xgds/xgds_subsea/apps/geocamTrack/importer/trackImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/NAV.yaml -v Nautilus -f %(flight)s_Nautilus'
    timeout: 300
    order: 3
    auth: false
  - name: 'Hercules NAV'
    filepath_pattern: 'processed/dive_reports/(?P<flight>H\d{4})/sampled/H\d{4}\.NAV\.M1\.sampled\.tsv'
    importer: '/home/xgds/xgds_subsea/apps/geocamTrack/importer/trackImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/NAV.yaml -v Hercules -f %(flight)s_Hercules'
    timeout: 300
    order: 3
    auth: false
  - name: 'Argus NAV'
    filepath_pattern: 'processed/dive_reports/(?P<flight>H\d{4})/sampled/H\d{4}\.NAV\.M2\.sampled\.tsv'
    importer: '/home/xgds/xgds_subsea/apps/geocamTrack/importer/trackImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/NAV.yaml -v Argus -f %(flight)s_Argus'
    timeout: 300
    order: 3
    auth: false
  - name: 'ECHO NAV'
    filepath_pattern: 'processed/dive_reports/H\d{4}/sampled/H\d{4}\.NAV\.M3\.sampled\.tsv'
    ignore: true
  - name: 'dive summary'
    filepath_pattern: 'processed/dive_reports/H\d{4}/H\d{4}-summary.txt'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/load_dive_summary.py'
    timeout: 300
    order: 8
  - name: 'event log'
    filepath_pattern: 'processed/eventlog/by-dive/all_eventlog_H\d{4}.*\.txt'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/eventLogCsvImportRunner.py'
    arguments: '-i %(filename)s -p -r -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/EventLog.yaml'
    timeout: 300
    order: 4
    auth: false
  - name: 'sample spreadsheet'
    filepath_pattern: 'processed/samples/\w*\d+_Samples\.xlsx'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/sampleSummaryImporter.py'
    timeout: 300
    order: 5
    auth: false
  - name: 'science chat'
    filepath_pattern: 'processed/eventlog/by-day/all_chatlog_\d{8}\.txt'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/sciChatCsvImportRunner.py'
    arguments: '-i %(filename)s -r -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/SciChat.yaml'
    timeout: 300
    order: 4
    auth: false
  - name: 'raw acoustic mbes screenshots'
    filepath_pattern: '[\d\.]+/raw/acoustic/mbes/screenshots/\d{8}_\d{4}.*.[png|JPG]'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Acoustic -t dateparser -r "(\d{8})_(\d{4}).*.[png|JPG]"'
    timeout: 300
    order: 5
    auth: true
  - name: 'raw acoustic screengrabs'
    filepath_pattern: '[\d\.]+/raw/acoustic/ScreenGrabs/\d{8}_\d{4}.*.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Acoustic -t dateparser -r "(\d{8})_(\d{4}).*.png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture pngs hercules'
    filepath_pattern: '[\d\.]+/processed/capture_pngs/capture_(\d{8})/cam1_[\d]{14}.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Hercules -t dateparser -r "cam1_(\d+).png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture pngs argus'
    filepath_pattern: '[\d\.]+/processed/capture_pngs/capture_(\d{8})/cam2_[\d]{14}.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Argus -t dateparser -r "cam2_(\d+).png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture highlights top level herc'
    filepath_pattern: '[\d\.]+/processed/capture_highlights/cam1_[\d]{14}.*.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Hercules -t dateparser -r "cam1_(\d+).*.png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture highlights top level argus?'
    filepath_pattern: '[\d\.]+/processed/capture_highlights/cam2_[\d]{14}.*.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Argus -t dateparser -r "cam2_(\d+).*.png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture highlights herc'
    filepath_pattern: '[\d\.]+/processed/capture_highlights/.*/cam1_[\d]{14}.*.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Hercules -t dateparser -r "cam1_([\d]{14}).*.png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture highlights argus'
    filepath_pattern: '[\d\.]+/processed/capture_highlights/.*/cam2_[\d]{14}.*.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-c Argus -t dateparser -r "cam2_([\d]{14}).*.png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture highlights'
    filepath_pattern: '[\d\.]+/processed/capture_highlights/.*/[\d]{8}_[\d]{4}.*.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-t dateparser -r  "(\d{8})_(\d{4}).*.png"'
    timeout: 300
    order: 5
    auth: true
  - name: 'capture highlights'
    filepath_pattern: '[\d\.]+/processed/capture_highlights/.*/[\d]{8}_[\d]{4}.*.JPG'
    importer: '/home/xgds/xgds_subsea/apps/xgds_image/importer/import_image.py'
    arguments: '-t dateparser -r  "(\d{8})_(\d{4}).*.JPG"'
    timeout: 300
    order: 5
    auth: true
  - name: 'samples labphotos'
    filepath_pattern: '[\d\.]+/processed/samples/NA[\d]{3}-[\d]{3}/labphotos/DSCN[\d]{4}.JPG'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/import_sample_photo.py'
    arguments: '-i'
    timeout: 300
    order: 5
    auth: true
  - name: 'link vidcaps to samples'
    filepath_pattern: '[\d\.]+/processed/samples/NA\d+-\d+/vidcaps/cam1_[\d]{14}.png'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/import_sample_photo.py'
    timeout: 300
    order: 6
    auth: true
  - name: 'tempprobe'
    filepath_pattern: '[\d\.]+/raw/datalog/.*\.TEM'
    importer: '/home/xgds/xgds_subsea/apps/xgds_core/importer/csvImportRunner.py'
    arguments: '-s -i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/TempProbe.yaml'
    timeout: 300
    order: 3
    auth: false
  - name: 'O2S'
    filepath_pattern: '[\d\.]+/processed/dive_reports/.*/sampled/(?P<flight>H\d{4}).O2S.sampled.tsv'
    importer: '/home/xgds/xgds_subsea/apps/xgds_core/importer/csvImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/O2S.yaml -f %(flight)s_Hercules'
    timeout: 300
    order: 2
    auth: false
  - name: 'CTD'
    filepath_pattern: '[\d\.]+/processed/dive_reports/.*/sampled/(?P<flight>H\d{4}).CTD.sampled.*.tsv'
    importer: '/home/xgds/xgds_subsea/apps/xgds_core/importer/csvImportRunner.py'
    arguments: '-i %(filename)s -c /home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/CTD.yaml -f %(flight)s_Hercules'
    timeout: 300
    order: 2
    auth: false
  - name: 'tgt files'
    filepath_pattern: '[\d\.]+/raw/nav/hypack/.*\.tgt'
    importer: '/home/xgds/xgds_subsea/apps/xgds_subsea_app/importer/tgtToMapLayer.py'
    arguments: '-f %(filename)s'
    timeout: 300
    order: 5
    auth: true
  - name: 'chatlog_html' # ALWAYS SKIP
    filepath_pattern: '[\d\.]+/raw/chatlog/.*/.*/.*\.html'
    ignore: true
  - name: 'DS_Store'
    filepath_pattern: '.*/\.DS_Store'
    ignore: true
  - name: 'chatlog' # TODO IMPLEMENT
    filepath_pattern: '[\d\.]+/processed/eventlog/by-dive/all_chatlog_.*\.txt'
    importer: '/home/xgds/xgds_subsea/apps/xgds_notes/importer/import_notes.py'
    timeout: 300
    order: 4
    auth: false
    ignore: true
