bridges:
  her:
    host: '127.0.0.1'
    port: 41236
    channel: 'xgds:her'
    verbose: false
  nav:
    host: '127.0.0.1'
    port: 41237
    channel: 'xgds:nav'
    verbose: false
  tem:
    host: '127.0.0.1'
    port: 41240
    channel: 'xgds:tem'
    verbose: false
  ctd:
    host: '127.0.0.1'
    port: 41241
    channel: 'xgds:ctd'
    verbose: false
  event:
    host: '127.0.0.1'
    port: 41250
    channel: 'xgds:event'
    verbose: false
  chat:
    host: '127.0.0.1'
    port: 41242
    channel: 'xgds:scichat'
    verbose: false
  grab:
    host: '127.0.0.1'
    port: 41243
    channel: 'xgds:grab'
    verbose: true
