# Empty string for host enables listening on all network interfaces rather than one specific interface

bridges:
  her:
    # HER   13060
    host: ''
    port: 13060
    channel: 'xgds:her'
    verbose: false
  nav:
    # NAV   13069
    host: ''
    port: 13069
    channel: 'xgds:nav'
    verbose: false
  tem:
    # TEM   13065
    host: ''
    port: 13065
    channel: 'xgds:tem'
    verbose: false
  ctd:
    # CTD   13064
    host: ''
    port: 13064
    channel: 'xgds:ctd'
    verbose: false
  event:
    # EVENT 13067
    host: ''
    port: 13067
    channel: 'xgds:event'
    verbose: true
  chat:
    # CHAT  13077
    host: ''
    port: 13077
    channel: 'xgds:scichat'
    verbose: false
  grab:
    # GRABHD 13078
    host: ''
    port: 13078
    channel: 'xgds:grab'
    verbose: false
