# Empty string for host enables listening on all network interfaces rather than one specific interface

bridges:
  her:
    # DATA_TYPE="HER"    IN_SOCKET=31236
    host: ''
    port: 31236
    channel: 'xgds:her'
    verbose: false
  nav:
    # DATA_TYPE="NAV"    IN_SOCKET=31237
    host: ''
    port: 31237
    channel: 'xgds:nav'
    verbose: false
  tem:
    # DATA_TYPE="TEM"    IN_SOCKET=31235
    host: ''
    port: 31235
    channel: 'xgds:tem'
    verbose: false
  ctd:
    # DATA_TYPE="CTD"    IN_SOCKET=31233
    host: ''
    port: 31233
    channel: 'xgds:ctd'
    verbose: false
  event:
    # DATA_TYPE="EVENT"  IN_SOCKET=31234
    host: ''
    port: 31234
    channel: 'xgds:event'
    verbose: true
  chat:
    # DATA_TYPE="CHAT"   IN_SOCKET=30100
    host: ''
    port: 30100
    channel: 'xgds:scichat'
    verbose: false
  grab:
    # DATA_TYPE="GRABHD" IN_SOCKET=60005
    host: ''
    port: 60005
    channel: 'xgds:grab'
    verbose: false
