# shore side UDP repeater config from OET spreadsheet first tab:
# BNAV   13076
# HER    13060
# CTD    13064
# TEM    13065
# INNAV  13066
# EVENT  13067
# USBL   13068
# NAV    13069
# CPU    13070
# ENV    13071
# WNCH   13072
# WTHR   13073
# SSV    13074
# MDM    13075
# CHAT   13077
# GRABHD 13078

#fileExt: INNAV
#outputs:
#        - source: 
#          address: 127.0.0.1
#          port: 13066
#          term: \r\n
#          headers: True
#
#---

fileExt: HER
outputs:
        - source: ~
          address: 127.0.0.1
          port: 13060
          term: \r\n
          headers: True

---

fileExt: NAV
outputs:
        - source: ~
          address: 127.0.0.1
          port: 13069
          term: \r\n
          headers: True

#---
#
#fileExt: USBL
#outputs:
#        - source: ~
#          address: 127.0.0.1
#          port: 13068
#          term: \r\n
#          headers: True
#
#---
#
#fileExt: DNV
#outputs:
#        - source: ~
#          address: 127.0.0.1
#          port: 
#          term: \r\n
#          headers: True

---

fileExt: TEM
outputs:
        - source: ~
          address: 127.0.0.1
          port: 13065
          term: \r\n
          headers: True

---

fileExt: CTD
outputs:
        - source: ~
          address: 127.0.0.1
          port: 13064
          term: \r\n
          headers: True
---

fileExt: EVENT
outputs:
        - source: ~
          address: 127.0.0.1
          port: 13067
          term: \r\n
          headers: True

---

fileExt: CHAT
outputs:
        - source: ~
          address: 127.0.0.1
          port: 13077
          term: \r\n
          headers: True

#---
#
#fileExt: GRABHD
#outputs:
#        - source: ~
#          address: 127.0.0.1
#          port: 13078
#          term: \r\n
#          headers: True
